### PR TITLE
New keyword: precision

### PR DESCRIPTION
**Pull request by pkuczynski**
`precision` allows limiting number of digits after decimal point

### CODE REVIEW

**Comment by pkuczynski** [comment]
@epoberezkin I have an issue with my test. I pretty much copied from `range.spec.ts` but still cant get it running :(

**Comment by epoberezkin** [comment]
You should be able to use, for example, `multipleOf: 0.01` to limit to 2 digits (there is `multipleOfPrecision` option that might be helpful).

> I have an issue with my test. I pretty much copied from range.spec.ts but still cant get it running

What exactly is the problem? Can it be down to imprecise arithmetics?

**Comment by epoberezkin** [comment]
Also, there are several other places you need to add any new keyword to - search for any existing keyword name.

**Comment by epoberezkin** [comment]
Closing it as mostly duplicating what can be done with multipleOf.

@pkuczynski please let me know if there is a use case it doesn't cover - we can re-open.

**Pull request closed without merging**
